name: Build and Publish Sample Application

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Setup Java SDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build frontend
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc
          npm ci
          npm run build
        working-directory: frontend

      - name: Copy frontend artifacts
        run: |
          mkdir -p backend/sirius-web-frontend/src/main/resources/static
          cp -R frontend/build/* backend/sirius-web-frontend/src/main/resources/static

      - name: Build backend with Maven
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn -U -B clean verify -f backend/pom.xml --settings settings.xml
          mkdir staging
          cp backend/sirius-web-sample-application/target/sirius-web-sample-application-*-SNAPSHOT.jar staging/sirius-web-sample-application.jar

      - name: Publish sample application
        uses: actions/upload-artifact@v2
        with:
          name: SiriusWebSample
          path: staging
